### ISSUE TITLE
Title page seems to be broken in TeX Live 2018

### ISSUE THREAD

**Issue by Ashymad** [polaksta/beamer-AGH#1]
The lines on the left are broken.

![image](https://user-images.githubusercontent.com/15618637/47150729-d3eb1280-d2d7-11e8-99b3-5f8a0666eb2c.png)

**Comment by polaksta** [comment]
I have TeX Live 2018 on Linux I have not noticed this issue

**Comment by Ashymad** [comment]
I cannot reproduce this issue anymore. It might have been caused by the specific version of TeX Live that I had (on Arch Linux). I'll close this.
